################################################################################
#   Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################

global:
  onSuccess: on-success default implementation
  onFailure: on-failiure default implementation
  trustStore : path/to/truststore
  tenant :
    domain : domain
    tenantID : 1234
    username : username
    password : password

serverGroup :
  -
    name : gateway_mgt
    hosts :
      - https://10.0.10.13:9443
      - https://10.0.10.13:9443
    trustsore : path/to/custom/truststotre
  -
    name : gateway_worker
    hosts :
      - https://10.0.10.13:9443
      - https://10.0.10.14:9443
  -
    name : gateway
    hosts:
      - https://gateway.cloud.wso2.com:443
    trustsore : path/to/custom/truststotre
  -
    name : keymanager
    hosts :
      - https://keymanager.cloud.wso2.com:443
    trustsore : path/to/custom/truststotre

taskGroup :
  -
    enable : true
    name : xyz
    className : org.wso2.TestClass
    triggerType: simple
    trigger : 60m
    #trigger : * 60 * * * *
    onResult : custom.onResult.implementation
    servers : [gateway, keymanager]
    taskParams :
       key : value
       key2 : value2
       severity : 2
  -
    enable : true
    name : abc
    className : org.wso2.LoginTest
    triggerType: cron
    trigger : 60m
    onResult : custom.onResult.implementation
    servers : [gateway_mgt, gateway_worker, gateway,keymanager]
    taskParams :
       key : value
       key2 : value2
       severity : 1
